[fir] Add copyright header on code files
MentorEmbedded/meta-tracing pull request #106
Opened 2021-12-22 04:50 UTC by ansar-rasool

JIRA-ID: SB-17889

Signed-off-by: ansar-rasool <ansar_rasool@mentor.com>

2021-12-22 05:47 UTC, ansar-rasool commented
List of unchanged files:

README.md
qt5-layer/recipes-qt/qt5/qtbase/0001-add_tracepoint_layer.patch
qt5-layer/recipes-qt/qt5/qtdeclarative/0001-add_tracepoint_layer.patch
recipes-multimedia/gstreamer/gstreamer1.0/0001-Add-optional-LTTng-support-in-configure.patch
recipes-multimedia/gstreamer/gstreamer1.0/0001-gstreamer1.0-meson-add-lttng-tracepoints-support.patch
recipes-multimedia/gstreamer/gstreamer1.0/0002-Add-basic-LTTng-tracepoints-infrastructure.patch
recipes-multimedia/gstreamer/gstreamer1.0/0003-Add-gst_flow-LLTng-tracepoints.patch
recipes-multimedia/gstreamer/gstreamer1.0/0004-gst_flow_data-LLTng-tracepoints.patch
recipes-multimedia/gstreamer/gstreamer1.0/0005-Support-for-gst_flow_event-LLTng-tracepoints.patch
recipes-multimedia/gstreamer/gstreamer1.0/0006-Added-support-for-gst_flow_event_latency-and-gst_flo.patch
recipes-multimedia/gstreamer/gstreamer1.0/0007-Added-GST_TRACEPOINT_ENABLED-macro.patch
recipes-multimedia/gstreamer/gstreamer1.0/0008-Added-support-for-gst_flow_event_caps-LTTng-tracepoi.patch
recipes-multimedia/gstreamer/gstreamer1.0/0009-Added-event-type-field-to-gst_flow_event_qos-event-r.patch
recipes-multimedia/gstreamer/gstreamer1.0/0010-Added-gst_latency_measurement_start-end-passed-event.patch
recipes-multimedia/gstreamer/gstreamer1.0/0011-Added-latency-probe-tracepoint-event.patch

2021-12-22 12:41 UTC, abelal requested changes
None of the currently accepted identifiers mentioned on the spdx.org use the '+' sign. @ansar-rasool please adjust.

2021-12-22 12:41 UTC, abelal commented on recipes-multimedia/gstreamer/gstreamer1.0_1.16%.bbappend
> +# SPDX-License-Identifier: LGPL-2.0+
this is deprecated. please have a look at https://spdx.org/licenses/ we need to use LGPL-2.0-or-later

2021-12-22 12:41 UTC, abelal commented on recipes-multimedia/gstreamer/gstreamer1.0_1.16.3.bbappend
> +# SPDX-License-Identifier: LGPL-2.0+
deprecated identifier

2021-12-22 12:41 UTC, abelal commented on qt5-layer/recipes-qt/qt5/qtwayland_git.bbappend
> +# SPDX-License-Identifier: GFDL-1.3 AND BSD AND ( GPL-3.0 AND The-Qt-Company-GPL-Exception-1.0 OR The-Qt-Company-Commercial ) AND ( GPL-2.0+ OR LGPL-3.0 OR The-Qt-Company-Commercial )
GPL-2.0+ is deprecated

2021-12-22 12:48 UTC, abelal commented
Please note that I've mentioned only three instances using + in the review comments but there are others. Please accommodate.

2021-12-23 12:28 UTC, abelal approved these changes

2021-12-23 14:18 UTC, merged